name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Configure Git identity
        run: |
          git config --global user.email "marcelohenrique.backend@gmail.commarcelohenrique.backend@gmail.com"
          git config --global user.name "dev-celo"
      - name: Install dependencies
        run: npm ci
      - name: Build web-app
        run: npm run build
      - name: Deploy
        run: npm run deploy
